### ISSUE TITLE
Reply To Header Not Sent

### ISSUE THREAD

**Issue by khamasaki** [Paubox/paubox-node#12]
Setting a reply to header on the message has no effect. It seems to be because of this line:

https://github.com/Paubox/paubox-node/blob/master/src/service/emailService.js#L66

where it is trying to set it to the `reply_to` property of the message object. However, if you look at the message object, it has this:

https://github.com/Paubox/paubox-node/blob/master/src/data/message.js#L6

so the property should actually be `replyTo`

**Comment by vighneshtrivedi2004** [comment]
Thanks @khamasaki for reporting the issue. Raised PR #13 to fix this.

**Comment by khamasaki** [comment]
Thanks for the quick response!
